name: Run tests with coverage

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist
          npm install

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Build frontend
        run: npm run build

      - name: Create SQLite database file
        run: mkdir -p database && touch database/database.sqlite

      - name: Run migrations
        run: php artisan migrate --no-interaction

      - name: Seed database
        run: php artisan db:seed --no-interaction

      - name: Run tests with coverage
        run: vendor/bin/phpunit --coverage-cobertura=coverage.xml

      - name: Upload coverage to qlty.sh
        uses: qltysh/qlty-action/coverage@v1
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: coverage.xml
